### ISSUE TITLE
查询出错，一直报告方法不存在。

### ISSUE THREAD

**Issue by zxq911** [thinkcmf/thinkcmf#1]
Call to undefined method app\user\model\UserModel::getPk()， 

     * @param array  $alias      别名定义（已经废弃）
     * @param string $joinType   JOIN类型
     * @return BelongsTo
     */
    public function belongsTo($model, $foreignKey = '', $localKey = '', $alias = [], $joinType = 'INNER')
    {
        // 记录当前关联信息
        $model      = $this->parseModel($model);
        $foreignKey = $foreignKey ?: $this->getForeignKey($model);        
        $localKey   = $localKey ?: (new $model)->getPk();     //该方法一直调用出错。原因未知。
        return new BelongsTo($this, $model, $foreignKey, $localKey, $joinType);
    }

**Comment by thinkcmf** [comment]
已经修复
