### ISSUE TITLE
开启七牛储存后前台编辑头像与数据库地址不对应。

### ISSUE THREAD

**Issue by zz7628** [thinkcmf/thinkcmf#103]
例如：
七牛地址：http://or5l0m0tz.bkt.clouddn.com/avatar/20170608%5C5d3f876cd7d538e2212751e00c24dc33.png

本地数据库则是：avatar/20170608\5d3f876cd7d538e2212751e00c24dc33.png

七牛地址日期后是：%5c，数据库则是：\

**Comment by thinkcmf** [comment]
@zz7628 已经修复请测试，没有问题后，请关闭 issue.
