### ISSUE TITLE
HomeBase基础类 自动定位模板文件方法 解析路径出现问题。

### ISSUE THREAD

**Issue by xskjs888** [thinkcmf/thinkcmf#11]
经过莫名的操作后， 自动定位模板文件方法
private function parseTemplate($template)
返回的模板路径中， 含有  “\\” 。导致 模板数据 more 无法读取

例如： feach(':index') 模板 

解析后正确路径
themes/simpleboot3/portal/index.html

出现解析错误后
themes/simpleboot3/portal\\index.html

**Comment by thinkcmf** [comment]
@xskjs888 已经修复,请测试
