### ISSUE TITLE
官网密码重置邮件发送失败

### ISSUE THREAD

**Issue by qq907274532** [thinkcmf/thinkcmf#118]
![image](https://user-images.githubusercontent.com/8018438/27120535-8c13e944-5116-11e7-935c-7ac3fd2d0241.png)

**Comment by thinkcmf** [comment]
@qq907274532 检查自己的后台邮件配置，确保配置没有问题，这种问题应该是邮件配置问题

**Comment by qq907274532** [comment]
这个是你们官网出现的问题

**Comment by thinkcmf** [comment]
@qq907274532 已经可以了
