### ISSUE TITLE
导航标签<navigationMenu> 在模板中，多次使用，出现问题。

### ISSUE THREAD

**Issue by xskjs888** [thinkcmf/thinkcmf#13]
页面有两个导航，底部有一个。 

顶部导航，用<navigationMenu>标签循环列出，正常。

底部导航，再次用<navigationMenu>标签列出，出现问题。会受第一个导航标签的影响。

顶部导航代码
<navigation nav-id="1" root="">
        <navigationMenu root="li">
            <a href="{$menu.href|default='javascript:;'}" target="{$menu.target|default=''}">
                {$menu.name|default=''}
            </a>
        </navigationMenu>
    </navigation>

底部导航代码

<navigation nav-id="1" root="">
                <navigationMenu root="li">
                    <if condition="$menu.id neq 15">
                        <a href="{$menu.href|default='javascript:;'}" target="{$menu.target|default=''}">
                            {$menu.name|default=''}
                        </a>
                    </if>
                </navigationMenu>
            </navigation>

判断失效。、 下面的标签。 <li>内的 text() 值   受 上面的标签影响。

**Comment by thinkcmf** [comment]
@xskjs888 这个会不会是 id,设置的问题,jQuery使用时没有弄个好选择器,QQ 找老猫

**Comment by thinkcmf** [comment]
@xskjs888 已经修复,请测试
