### ISSUE TITLE
插件demo不能用

### ISSUE THREAD

**Issue by yangguangwuwu** [thinkcmf/thinkcmf#14]
插件demo不能用，不能安装   php5.6 报错500
Fatal error: Call to undefined function cmf_add_template_file_suffix() in C:\Users\Administrator\Desktop\thinkcmf5\thinkcmf\simplewind\cmf\common.php on line 1116
未定义的函数

**Comment by yangguangwuwu** [comment]
创建一个这函数
function cmf_add_template_file_suffix($str){
	return ROOT_PATH.'public/'.$str;
}

**Comment by yangguangwuwu** [comment]
点击管理 插件报错

**Comment by thinkcmf** [comment]
@yangguangwuwu 那个演示表,回来在演示插件的安装时加一下sql 导入
