### ISSUE TITLE
文章管理index页面  排序 有一处未改， 

### ISSUE THREAD

**Issue by xskjs888** [thinkcmf/thinkcmf#141]
‘’\<notempty name="term"\>
        \<th width="50"\>{:lang('SORT')}\</th\>
\</notempty\>‘’
下边排序按钮那也是  term
附加：
文章管理页面标题没给宽度。页面列数有点多，不够简洁。  
操作略有不便， 选择分类，点搜索后，点编辑。 点返回， 出现错误。

‘’此网页需要使用您之前输入的数据才能正常显示。您可以重新发送这些数据，不过，这么做会重复执行此网页之前执行过的所有操作。‘’

小白建议，选择分类的时候，就自动提交。 保留一个条件 session 以后每次进来，不用重复一些操作。

**Comment by jsRuner** [comment]
标题宽度不设定是正常的，主要考虑标题可能比较长。 至于搜索，还是保持现状吧。这样搜索思路一致。 如果分类自动提交，则其他条件其实也需要一致化。那搜索按钮其实可以删除了
