### ISSUE TITLE
.json文件修改时，后台不能更新

### ISSUE THREAD

**Issue by ZhangHblog** [thinkcmf/thinkcmf#15]
当我把json 文件里面内容全部删掉，重新写了之后，后台设计更新后  删掉的那部分  还是显示，只有模版重新安装后 ， 后台才能更新

**Comment by thinkcmf** [comment]
@ZhangHblog 已经确认稍后修复,之前是考虑到用户可能会添加数据

**Comment by thinkcmf** [comment]
@ZhangHblog 已经修复，请确认
