### ISSUE TITLE
邮箱注册，获取验证码出错

### ISSUE THREAD

**Issue by llrg222** [thinkcmf/thinkcmf#150]
点击获取验证码，要等很久才有反应，然后报错
邮箱验证码发送失败：SMTP Error：data not accepted. SMTP server error:DATA END command failed Detail:DT: SPM 163 SMTP9,DcCowAC1zPZLlpzy+n+Mw--,12427s2 1499082457,please see ............

点击获取邮箱验证码按钮，很久才有反应，这是什么原因

**Comment by suptime** [comment]
这是被拦截了，不是程序代码问题
