### ISSUE TITLE
上传图片Failed to open output stream！

### ISSUE THREAD

**Issue by lanhuazhidi** [thinkcmf/thinkcmf#16]
{"code":0,"msg":"Failed to open output stream！","data":"","url":"","wait":3}
{"code":0,"msg":"Failed to open output stream！","data":"","url":"","wait":3}
{"code":0,"msg":"Failed to open output stream！","data":"","url":"","wait":3}

**Comment by thinkcmf** [comment]
@lanhuazhidi 测试一下,已经更新
