### ISSUE TITLE
模板的挂件type为array时，item不支持其他类型

### ISSUE THREAD

**Issue by yuandalu** [thinkcmf/thinkcmf#164]
array下item使用 dataSource 不生效，弹不出选择界面，只能自己输入
希望能无限极的支持，不管是多少层，所有的type都应该生效

这个说的是挂件，我没测试模板变量是不是也存在这个问题，模板变量应该也支持无限级的类型

**Comment by thinkcmf** [comment]
@yuandalu 已经修复请测试
