### ISSUE TITLE
后台登录页面在IE、QQ、360等浏览器下有问题

### ISSUE THREAD

**Issue by marisa0208** [thinkcmf/thinkcmf#168]
在这几款浏览器下后台输入用户名、密码、验证码后点击登录，网页没反应。后测试发现虽然没跳转也没任何提示，用户信息已记入session里，再次在当前浏览器下直接输入后台的地址会直接进入后台。在火狐、谷歌、欧鹏、safari下均没这个问题。

**Comment by thinkcmf** [comment]
@marisa0208 能不能联系我，我来远程看一下

**Comment by thinkcmf** [comment]
@marisa0208  已经确认，我们来修复一下
