### ISSUE TITLE
更新后台菜单时失败，请修改获取数据的方式

### ISSUE THREAD

**Issue by mxok** [thinkcmf/thinkcmf#18]
后台菜单编辑提交保存的时候，editPost()方法，
Db::name('AdminMenu')->field(true)->update($this->request->param()); 修改为
Db::name('AdminMenu')->field(true)->update($this->request->post());
否则会报数据列不存在，因为用param获取参数时，获取的数组会附加 ["/admin/menu/editpost_html"]，再Update就直接报错了

**Comment by thinkcmf** [comment]
@mxok 已经修复,请测试

**Comment by mxok** [comment]
不知道为什么，我自己创建了一个应用，导入注解菜单，一直为空，感觉找不到控制器，想debug一下，没有搭建环境，能提供个思路，怎么找下问题

**Comment by mxok** [comment]
找到问题的原因了，所有非admin控制器都是使用admin*的方式查找的，文档中没有标注，后期需要特别标准，以免使用者不知道问题所在
