### ISSUE TITLE
thinkcmf5安装出现数据库执行错误

### ISSUE THREAD

**Issue by jztele** [thinkcmf/thinkcmf#187]
具体提示为“安装过程,共101个SQL执行错误,可能您在此数据库下已经安装过 CMF,”；错误内容有“ 1.创建数据表cmf_admin_menu 失败！”等各种数据表创建失败；将以前安装过的cmf数据库都删除了也不行

**Comment by thinkcmf** [comment]
@jztele 数据库什么版本？加一下群，反馈一下

**Comment by websw** [comment]
我也遇到这样的错误，之前没有安装过  107个SQL执行错误

**Comment by websw** [comment]
MYSQL: 5.5.53   本地运行  phpstudy  PHP7

**Comment by websw** [comment]
@thinkcmf 我的原因是MYSQL没有INNODB引擎 开启就好了
