### ISSUE TITLE
win10  php7 centos php 5.6均同一个错误

### ISSUE THREAD

**Issue by lifeha** [thinkcmf/thinkcmf#2]
![image](https://cloud.githubusercontent.com/assets/5966373/24577397/a6e92ae6-16ff-11e7-8748-599fc104fac9.png)

**Comment by thinkcmf** [comment]
你没看安装步骤,data/conf/database.php要自己加

**Comment by lifeha** [comment]
手册上写的是data/database.php.....

**Comment by thinkcmf** [comment]
@lifeha 以这个项目的 readme.md 为准
