### ISSUE TITLE
文章中使用prev_article最好是降序排列，否则会一直是第一篇文章

### ISSUE THREAD

**Issue by holyland2016** [thinkcmf/thinkcmf#211]
在postservice.php中修改
$article = $portalPostModel->alias('post')->field('post.*')
                ->where($where)
                ->order('id', 'DESC')
                ->find();

**Comment by jsRuner** [comment]
不是很明白意思。。。

**Comment by fatekao** [comment]
上一篇文章怎么调用啊？
