### ISSUE TITLE
幻灯片两次上传同一张图片错误

### ISSUE THREAD

**Issue by BigTreeGo** [thinkcmf/thinkcmf#214]
添加两张幻灯片图片，第一次和第二次用的相同的图片， 这两张图片都会被上传 ，但数据表记录的都是第一次上传的图片路径，删除一张幻灯片，它对应路径的图片也被删除，那么另一张幻灯片就不会有图片对应

**Comment by jsRuner** [comment]
相同的图片只保存一个。现在幻灯片的删除已经不操作图片了，图片操作需要自己去资源管理那里删除。
