### ISSUE TITLE
头一次安装，因为index.php的调试模式未关闭导致安装不成功。

### ISSUE THREAD

**Issue by xiwang6428** [thinkcmf/thinkcmf#215]
这个问题估计很多初入门的人都遇到，希望作者能在readme当中加入此提示。

**Comment by thinkcmf** [comment]
@xiwang6428 这个不应该，你能加一下官网群，反馈一下吗？@老猫

**Comment by xiwang6428** [comment]
此问题已解决，因为我使用了xdebug，把它关闭就好了。
