### ISSUE TITLE
用户后台管理模块，昵称属性值拼写错误

### ISSUE THREAD

**Issue by hebzh** [thinkcmf/thinkcmf#218]
用户后台管理模块，昵称属性值拼写错误，导致后台用户表看不到用户昵称！
![_20170803170314](https://user-images.githubusercontent.com/29971969/28914447-42652c48-786e-11e7-8e94-e76eb15b78cc.png)
![_20170803170348](https://user-images.githubusercontent.com/29971969/28914445-425116ea-786e-11e7-814e-cc8c00a677f6.png)
![_20170803170417](https://user-images.githubusercontent.com/29971969/28914446-42652950-786e-11e7-9b15-ca520d5fbd83.png)

**Comment by jsRuner** [comment]
最新的已经修复

**Comment by thinkcmf** [comment]
@hebzh 已经修复
