### ISSUE TITLE
后台模板设计，json文件中的数组数据，不能正常显示

### ISSUE THREAD

**Issue by shen55** [thinkcmf/thinkcmf#222]
后台模板设计，index.html文件对应的index.json文件中的变量，根据文档写为数组类型。
在后台，变量设置，点击设置的数组之后，数组中添加的数据不能正常显示。
我做了修改，已经可以正常显示。
\app\admin\controller\ThemeController.php文件的279~290
`//        $vars = [];
        if ($tab == 'var' && !empty($oldMore['vars']) && is_array($oldMore['vars'])) {

            if (isset($oldMore['vars'][$varName]) && is_array($oldMore['vars'][$varName])) {
                $items = $oldMore['vars'][$varName]['value'];
            }

            if (isset($oldMore['vars'][$varName]['item'])) {
                $item = $oldMore['vars'][$varName]['item'];
            }

        }`

**Comment by thinkcmf** [comment]
@shen55 已经更新，多谢
