### ISSUE TITLE
提示：虚拟主机下布署cmf一定要注意public目录不能设置为web目录问题。

### ISSUE THREAD

**Issue by xiwang6428** [thinkcmf/thinkcmf#223]
一般虚拟主机下不能自由设置web目录，所以布署cmf5要注意的问题就是public目录下的文件。
建议将public目录下的文件夹和文件搬下web目录下，不直接使用http://域名/public/index.php访问。
本人在测试退出登录时跳转出错，除此问题还暂不知道有无其他问题。

**Comment by thinkcmf** [comment]
@xiwang6428 这个要更改一些文件的，稍后加一下教程

**Comment by livepu** [comment]
这个确实很多虚拟机不方便啊。除非自己做vps。

**Comment by thinkcmf** [comment]
https://www.thinkcmf.com/topic/1449.html 看一下这个
