### ISSUE TITLE
setCookie 函数用 escape 来转义值，但 getCookie 函数没有 unescape 值

### ISSUE THREAD

**Issue by aiselo** [thinkcmf/thinkcmf#23]
所以这两个函数并不对称，建议 getCookie 函数返回值时先 unescape。

代码所在文件：
public/static/js/admin.js
public/static/js/frontend.js

**Comment by thinkcmf** [comment]
@aiselo 已经修复测试一下

**Comment by aiselo** [comment]
@
测试通过
