### ISSUE TITLE
虚拟机没权限，怎样改成不在public下运行呢？

### ISSUE THREAD

**Issue by livepu** [thinkcmf/thinkcmf#238]
虚拟机没什么权限修改web目录。能否自己改写一下运行代码呢？不知道怎么改。

**Comment by thinkcmf** [comment]
index.php 里有一个 CMF_ROOT,改到程序根目录，同时把 public里文件放到程序根目录

**Comment by thinkcmf** [comment]
https://www.thinkcmf.com/topic/1449.html

**Comment by livepu** [comment]
谢谢！这个很有用。
