### ISSUE TITLE
后台配置项返回格式出错,上传功能将不能正常使用

### ISSUE THREAD

**Issue by eggangel** [thinkcmf/thinkcmf#248]
showErrorMsg — ueditor.all.min.js:2738
系统是ubuntu14.04 x64，采用nginx+php+mysql的后台，使用thinkcmf5后台时，点击添加文章会报上述错误，webuploader.html下的showError = function (code)，返回值code=server，所有的文件均报错无法上传；

在Mac下的MAMP测试和windows下的wamp测试文件上传完全没问题，放到ubuntu服务器上就出错，请问这是什么原因？

**Comment by thinkcmf** [comment]
加一下QQ给你看看，可能是自己配置问题

**Comment by thinkcmf** [comment]
rewrite不支持吧
