### ISSUE TITLE
新安装的ThinkCMF，用户登录，提示500错误

### ISSUE THREAD

**Issue by hukang1206010217** [thinkcmf/thinkcmf#250]
发现是cmf_user_action函数报错
找到cmf_user_action这个函数，发现新数据并没有user_action这张表
请再安装sql中插入这张表

**Comment by thinkcmf** [comment]
你下载的是master吗？明天看看

**Comment by hukang1206010217** [comment]
是的，是的，master thinkcmf5.0 高考版
