### ISSUE TITLE
cmf\lib\Auth\check方法逻辑是不是有问题

### ISSUE THREAD

**Issue by wudihzh** [thinkcmf/thinkcmf#252]
+ name可以接受array类型的参数，但是下面的代码，如果name是数组不是有问题吗？
```php
$findAuthRuleCount = Db::name('auth_rule')->where([
    'name' => $name
])->count();
```

+ name可以接受逗号分隔的字符串，但是判断：
```php
if ($findAuthRuleCount == 0) {//没有规则时,不验证!
    return true;
}
```
放在将权限用逗号分隔成数组的代码前面，
auth_rule表里面应该没有逗号分隔的多个权限放在一起，那么如果我传进去逗号分隔的权限列表，是不是每次都返回true？

**Comment by thinkcmf** [comment]
@wudihzh 已经修复，请测试
