### ISSUE TITLE
安装过程,共107个SQL执行错误,可能您在此数据库下已经安装过 CMF,请查看问题后重新安装,或者 反馈问题

### ISSUE THREAD

**Issue by zhuluit** [thinkcmf/thinkcmf#255]
安装过程,共107个SQL执行错误,可能您在此数据库下已经安装过 CMF,请查看问题后重新安装,或者
反馈问题

**Comment by zhuluit** [comment]
mysql 5.6

**Comment by wudihzh** [comment]
提示都说你可能已经安装过了，进数据库检查一下

**Comment by zhuluit** [comment]
sql执行之后只成功建立了2各表，有cmf_theme 和 cmf_theme_file。

**Comment by zhuluit** [comment]
innodb设置问题，调整了2个数值，分别是  innodb_buffer_pool_size=1240M，innodb_log_file_size=512M。
重启之后，顺利完成安装。
