### ISSUE TITLE
thinkcmf部分问题。

### ISSUE THREAD

**Issue by noecs** [thinkcmf/thinkcmf#258]
1.在没有配置本地服务器虚拟主机的情况下。后台logout操作报错，原因：以当前的url为相对路径叠加了一次路径跳转导致报错。
2.问题：在后台发布文章或者发布页面的时候，提示的模板选择，模板是否可以添加别名，用来区分模板样式。开发文档部分对这个描述比较少。

**Comment by thinkcmf** [comment]
可以优化下

**Comment by thinkcmf** [comment]
@noecs 两个 问题都已经优化，请测试，如果还有问题，请重新打开这个 issue
