### ISSUE TITLE
list_order应该改float为int(10)

### ISSUE THREAD

**Issue by 6dao** [thinkcmf/thinkcmf#274]
app\install\data\thinkcmf.sql
第十行：
  `list_order` float unsigned NOT NULL DEFAULT '10000' COMMENT '排序ID',
应该改为：
  `list_order` int unsigned NOT NULL DEFAULT '10000' COMMENT '排序ID',
因为float没有unsigned，这时候还是会自动转为整形。

**Comment by thinkcmf** [comment]
@6dao 会统一修一下

**Comment by thinkcmf** [comment]
@6dao 已经修复
