### ISSUE TITLE
BaseController的第76行排序功能有bug.

### ISSUE THREAD

**Issue by xiwang6428** [thinkcmf/thinkcmf#284]
第76行：
$model->where([$pk => $key])->update($data);

这里用了$key值为主键值作搜索条件，这是不正确的，已测试是问题。

**Comment by thinkcmf** [comment]
@xiwang6428 这里并没有发现什么问题，你怎么提交的数据？

**Comment by xiwang6428** [comment]
没事，是我改写错了……
