### ISSUE TITLE
网站信息【$site_info 】变量，在插件中是否无效？

### ISSUE THREAD

**Issue by oMhuAaN** [thinkcmf/thinkcmf#310]
![image](https://user-images.githubusercontent.com/24907600/30622470-6a87f548-9de4-11e7-875c-913f1c3bb664.png)
这是报错提示
![image](https://user-images.githubusercontent.com/24907600/30622476-76dd0c16-9de4-11e7-9bea-dcc4c5ee2b2b.png)
这是 我的代码

**Comment by thinkcmf** [comment]
@oMhuAaN 已经优化
