### ISSUE TITLE
首页增加nav2  

### ISSUE THREAD

**Issue by duruigangduruigang** [thinkcmf/thinkcmf#32]
<navigation nav-id="2" root="ul" id="main-navigation" class="nav navbar-nav navbar-nav-custom">
    <navigationMenu root="li" class="menu-item menu-item-level-{$level}">
        <a href="{$menu.href|default=''}" target="{$menu.target|default=''}">{$menu.name|default=''}</a>
    </navigationMenu>
    <navigationFolder root="li" class="dropdown dropdown-custom dropdown-custom-level-{$level}" dropdown="ul"
                      dropdown-class="dropdown-menu dropdown-menu-level-{$level}">
        <a href="#" class="dropdown-toggle dropdown-toggle-{$level}" data-toggle="dropdown">
            {$menu.name|default=''}<span class="caret"></span>
        </a>
    </navigationFolder>
</navigation>
会报错

**Comment by thinkcmf** [comment]
@duruigangduruigang 已经修复
