### ISSUE TITLE
新建一套前台模板问题的几个疑问！

### ISSUE THREAD

**Issue by yihuankeji** [thinkcmf/thinkcmf#320]
新建一套模板后 在新建的模板目录 添加配置好manifest.json文件后，后台可以直接显示 安装好；选择默认后，前台还是一直访问simpleboot3模板？就算后台卸载simpleboot3也无效；后台模板都卸载了 为什么前台还会显示；缓存都清了；还有 每个模板配置 json，效率很好吗？，，，，

**Comment by thinkcmf** [comment]
@yihuankeji 
1.一直访问simpleboot3
```可能是你的后台模板切换插件打开了，你关了就可以了。```

2.后台模板都卸载了 为什么前台还会显示；
`这个主要是考虑到默认要给用户一个显示吧，其实安装只是配置一下模板数据，和真正使用没太大关系`

3.还有 每个模板配置 json，效率很好吗？
`模板配置 json只是安装时读取，运行时会走缓存，模板配置 json最大的目的是为了灵活性`
