### ISSUE TITLE
一个json配置文件只能配置一个array变量

### ISSUE THREAD

**Issue by ZhangHblog** [thinkcmf/thinkcmf#33]
配置第二个array变量时，第二个array不能添加修改数据

**Comment by ZhangHblog** [comment]
找到问题了
后台ThemeController.php

foreach ($more['widgets'] as $widgetName => $widget) {
                    if ($widgetName == $widgetName) {

 键值名： $widgetName  与传过来的 值 ：$widgetName  重复了

**Comment by thinkcmf** [comment]
@ZhangHblog 已经修复，请测试
