### ISSUE TITLE
后台文章上传图片失败问题！linux服务器 lamp环境 mod_rewrite也已经开启，在本地没问题啊

### ISSUE THREAD

**Issue by yihuankeji** [thinkcmf/thinkcmf#333]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)！

**Comment by thinkcmf** [comment]
@yihuankeji 看一下，是不是 php fileinfo扩展没有打开

**Comment by yihuankeji** [comment]
谢谢你的回答，已经开了 找到问题了；不过不理解，就是 本地做好之后，上传服务器；除了 本地 开发 测试  上传的图片 所在文件夹没有上传；都上传成功以后；重新上传图片，之前在本地上传过的图片 都会报错；新的图片可以

**Comment by yihuankeji** [comment]
5.0.170927版本url 美化是不是出问题了 后台设置

portal/Index/index | index$
 前台报错
非法请求:portal/index/index

上一个版本没有这个问题
