### ISSUE TITLE
大文件上传的timeout问题。

### ISSUE THREAD

**Issue by wurining** [thinkcmf/thinkcmf#337]
https://github.com/thinkcmf/thinkcmf/blob/2baf4904144fac13fd7b350cf3569b73db5ae38a/public/plugins/qiniu/lib/Qiniu.php#L50
该插件在上传大文件时可能会产生timeout问题，我认为应该把直接上传改为[七牛云分块上传](https://developer.qiniu.com/kodo/api/1286/mkblk)。

**Comment by thinkcmf** [comment]
这个稍后优化一下，让前台可以直接和七牛对接，而不在先上传到服务器，再传到七牛了

**Comment by wurining** [comment]
@thinkcmf 我希望可以做一个上传选项，用户选择是否在服务器做备份。考虑到大文件备份耗时较久，可以将大文件放一个队列后台上传。一点不成熟的小建议。

**Comment by thinkcmf** [comment]
@wurining 已经优化，现在可以直接传到云存储
