### ISSUE TITLE
[Tips]项目中使用的composer.phar过期的解决办法

### ISSUE THREAD

**Issue by wurining** [thinkcmf/thinkcmf#341]
项目中使用的composer.phar可能出现phar包过期现象，例如出现提示：
`Warning: This development build of composer is over 60 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.`

[解决方法：](https://stackoverflow.com/questions/19064731/how-to-run-composer-phar-self-update-in-travis)在项目文件夹下执行：`php composer.phar self-update`

**Comment by thinkcmf** [comment]
你升级呗

**Comment by wurining** [comment]
@thinkcmf 写个Tips，估计会有人遇到这个问题哈
