### ISSUE TITLE
模板-设计-添加变量-上传图片，上传图片点击不到。

### ISSUE THREAD

**Issue by wurining** [thinkcmf/thinkcmf#346]
当模板配置文件中图片的value为空时，图片缩略图为空白，因此点不到上传图片，可以判断下，如果没有图片则显示默认图片。

<img width="325" alt="2017-10-17 2 14 10" src="https://user-images.githubusercontent.com/26198634/31649527-e8a22f8a-b2d8-11e7-932c-616247ab897d.png">

**Comment by jsRuner** [comment]
版本是什么?我测试是ok的，最新的

**Comment by wurining** [comment]
@jsRuner 5.0.170927⬅️ThinkCMF版本

**Comment by jsRuner** [comment]
无法复现，换个浏览器试试?已经使用相同的版本。或者按f12检查下console的控制台报错信息。

**Comment by wurining** [comment]
@jsRuner 我把代码po出来。
这是后台模板index.html的json配置文件。
```
{
    "name": "首页",
    "action": "portal/Index/index",
    "description": "首页模板文件",
    "order": 1.0,
    "more": {
        "vars": {
            "img": {
                "title": "首页图",
                "value": "",
                "type": "image",
                "tip": "",
                "rule": {
                    "require": true
                }
            }
        }
    }
}
```
其中当img变量中value值为=>""时，后台在变量设置中，上传图片处会变成空白，通过chrome控制台检查元素，发现该位置的img标签中src属性也为空，因此无法点击上传。如下图：
<img width="325" alt="31649527-e8a22f8a-b2d8-11e7-932c-616247ab897d" src="https://user-images.githubusercontent.com/26198634/31807368-66546914-b533-11e7-9cb3-fc164319a4f4.png">

**Comment by jsRuner** [comment]
复制了你的代码，在我本地也是正常。

源代码已经对value做过为空的处理。具体位置如下：

thinkcmf/public/themes/admin_simpleboot3/admin/theme/functions.html

` <a href="javascript:uploadOneImage('图片上传','#js-{$widget}{$varName}-input');">
                                <if condition="empty($vars[$varName]['value'])">
                                    <img src="__TMPL__/public/assets/images/default-thumbnail.png"
                                         id="js-{$widget}{$varName}-input-preview"
                                         width="135" style="cursor: pointer"/>
                                    <else/>
                                    <img src="{:cmf_get_image_preview_url($vars[$varName]['value'])}"
                                         id="js-{$widget}{$varName}-input-preview"
                                         width="135" style="cursor: pointer"/>
                                </if>
                            </a>`

**Comment by wurining** [comment]
@jsRuner 好吧，问题很奇怪。不过这是个小问题，如果有新的情况出现我再打开问题。

**Comment by Minnchong** [comment]
![Uploading 微信图片_20231016151016.jpg…]()

**Comment by Minnchong** [comment]
![微信图片_20231016151016](https://github.com/thinkcmf/thinkcmf/assets/86814435/45853ee8-aacb-4d2f-b9b7-7c5273457540)
