### ISSUE TITLE
ThinkCMF 5.0.170927在IE9下后台登录不提示成功，无跳转动作

### ISSUE THREAD

**Issue by jiewuzhe02** [thinkcmf/thinkcmf#356]
http://thinkcmf/public/admin/public/login.html修改地址栏去掉 /public/login.html  刷新就进入了，session已保存登录信息，没有跳转.启动调试后 显示 Noty未定义

**Comment by jsRuner** [comment]
放弃ie吧。后台跳转动画使用了第三方组件。而这个组件使用了css3动画。然后ie又支持不好。

**Comment by thinkcmf** [comment]
已经修复
