### ISSUE TITLE
后台系统重大bug：搜索条件在分页中无法维持的问题

### ISSUE THREAD

**Issue by zjturn** [thinkcmf/thinkcmf#366]
复现步骤：1、后台中新增15个管理员，比如用户名从 A1-A15，
2、然后以A为关键字搜索用户，会搜索出2页共15个用户
3、之后点选第2页，上方检索条件会丢失，并且后台未接收到用户名检索条件

**Comment by thinkcmf** [comment]
@zjturn 已经修复请单独更新https://raw.githubusercontent.com/thinkcmf/thinkcmf/4a65cf65ea34a9359eabb96482535ded69aad186/app/admin/controller/UserController.php
