### ISSUE TITLE
验证码无法显示，报500错误

### ISSUE THREAD

**Issue by hellogxp** [thinkcmf/thinkcmf#370]
版本为
thinkcmf-5.0.170927
<img width="1282" alt="2017-11-20 8 43 59" src="https://user-images.githubusercontent.com/1506016/32997743-ae490c5a-cd59-11e7-8621-c43ea9943da2.png">

**Comment by masterZSH** [comment]
可能是session目录没写入权限 还有很多可能一步步排查啊 - -。

**Comment by thinkcmf** [comment]
@hellogxp php扩展问题，打开图片链接看报错就知道了
