### ISSUE TITLE
使用自动安装将sql写入数据库时出现问题

### ISSUE THREAD

**Issue by galaxyhao** [thinkcmf/thinkcmf#376]
使用的是云数据库，要求必须有主键，所以写入数据时会报1173 - This table type requires a primary key错误
云数据库时腾讯云的TDSQL，
https://cloud.tencent.com/document/product/237/4914

**Comment by iokakaxi** [comment]
安装过程,共108个SQL执行错误,可能您在此数据库下已经安装过 CMF,

**Comment by thinkcmf** [comment]
@galaxyhao 稍后再针对此类数据库做处理吧，先在本地安装好，再移动到你云数据库吧

**Comment by thinkcmf** [comment]
已经修复
