### ISSUE TITLE
success带参数跳转出错

### ISSUE THREAD

**Issue by slsnpro** [thinkcmf/thinkcmf#377]
版本: 5.0.170906

## 继承AdminBaseController
$this->success带参数跳转出错: 参数没有添加到url
$this->redirect带参数跳转正常.

**Comment by thinkcmf** [comment]
@slsnpro 你怎么用的呢？可否贴一下代码，还有最好升级到最新的版本

**Comment by slsnpro** [comment]
版本: 5.0.170927
$this->success('sa', url('/user/admin_index/index', ['id' => 1])); // YES: 返回的链接有带参数
$this->success('sa', '/user/admin_index/index', ['id' => 1]); // NO: 返回的链接没有带参数
$this->redirect('/user/admin_index/index', ['id' => 1]); // YES: 跳转的链接有带参数
