### ISSUE TITLE
后台编辑器上传图片 URL自动附加域名问题 

### ISSUE THREAD

**Issue by xunni1000** [thinkcmf/thinkcmf#384]
多个域名同时绑定一个站点. 比如 A.COM   B.COM    C.COM

用A.com 安装thinkcmf .

用任一绑定的域名登陆后台,新增文章.
编辑器里面上传图片

上传成功后在编辑器里面看HTML代码
src = /upload/20171215/49d39cee9dad57cbbbfc072c76a992cd.png

然后提交文章.
那么到前台显示图片
看到图片的src =http://A.com/upload/20171215/49d39cee9dad57cbbbfc072c76a992cd.png

无论你是用哪个域名登陆,最后都会附加域名,而且一定是当初安装thinkcmf时候用的域名
而且一定是http协议

这让我使用**https**的非常尴尬.浏览器会报错.

这样自动附加域名还有一个不好的地方.就是那天我有个域名不用了,或者需要换域名,那么我文章里面的图片的src全部都需要替换下.

直接
src = /upload/20171215/49d39cee9dad57cbbbfc072c76a992cd.png
这样不好么,无论是用https还是http都是兼容的
或者我域名无论怎么变都是兼容的,
为啥一保存就自动附加域名了?

**Comment by thinkcmf** [comment]
你看到的是表面，cmf 内部已经处理了这样的问题，它会自己切换的，数据库里的路径保存的其实是相对路径，只是显示出来自动加了域名
