### ISSUE TITLE
API添加文章收藏

### ISSUE THREAD

**Issue by ucloser** [thinkcmf/thinkcmf#386]
![default](https://user-images.githubusercontent.com/34562123/34029726-ef123644-e1a4-11e7-8e23-5836d824554d.png)
添加ID参数然后显示未定义table参数 在接口57行处把table改成table_name；
![default](https://user-images.githubusercontent.com/34562123/34029791-37a2fc18-e1a5-11e7-89d6-9736075cc026.png)
description必传内容缩略可以改成可传。。

**Comment by thinkcmf** [comment]
@ucloser 以后请在 thinkcmfapi 项目反馈 api 的问题
