### ISSUE TITLE
模板管理-变量数据为array时删除出错，代码里出现明显的命名错误

### ISSUE THREAD

**Issue by qianxiaocang** [thinkcmf/thinkcmf#392]
->app\admin\controller\ThemeController.php

544行开始

<pre><code>
if ($tab == 'var') {
            foreach ($more['vars'] as $mVarName => $mVar) {

                if ($mVarName == $varName && $mVar['type'] == 'array') {
                    if (!empty($var['value']) && is_array($var['value']) && isset($var['value'][$itemIndex])) {
                        array_splice($more['vars'][$mVarName]['value'], $itemIndex, 1);
                    } else {
                        $this->error('指定数据不存在!');
                    }
                    break;
                }
            }
        }
</code></pre>
foreach中value值为mVar，而if中的value变为了var，导致删除变量数据一致报错。请注意！

**Comment by thinkcmf** [comment]
@qianxiaocang  dev已经修复
