### ISSUE TITLE
thinkcmf在使用cdn加速js样式后,使用后台文章编辑器时无法加载编辑器配置

### ISSUE THREAD

**Issue by myiskkz** [thinkcmf/thinkcmf#394]
正常情况下应该加载http://www.xxx.com/user/Ueditor/upload?action=config&&noCache=1514607408547

而使用cdn加速后，它加载的http://cdn.xxx.com/user/Ueditor/upload?action=config&&noCache=1514607408547

而这个配置文件时php输出的不是静态配置文件，加载不了就无法使用

**Comment by thinkcmf** [comment]
@myiskkz  已经修复,这个文件单独更新一下就可以了https://github.com/thinkcmf/thinkcmf/blob/dev/public/static/js/ueditor/ueditor.config.js
