### ISSUE TITLE
后台登录窗口验证码无法显示问题

### ISSUE THREAD

**Issue by cflee008** [thinkcmf/thinkcmf#395]
如题，安装成功后后台登录窗口无法显示验证码是什么问题
![108a5ad6-de91-4172-88e1-4a3a78183be1](https://user-images.githubusercontent.com/22695175/34550106-201df10c-f149-11e7-9e9e-da95ee436e43.png)

**Comment by thinkcmf** [comment]
@cflee008 多半是自己配置问题， FAQ已经上线https://www.kancloud.cn/thinkcmf/faq/493505

**Comment by ejzhang** [comment]
关闭调试后不显示验证码
[https://www.thinkcmf.com/topic/2152.html](url)
