### ISSUE TITLE
关于热门文章会出现重复已经解决了。

### ISSUE THREAD

**Issue by Thomastar** [thinkcmf/thinkcmf#396]
app\portal\service\ApiService.php

92 行左右
        $articles = $portalPostModel->alias('post')->field($field)
            ->join($join)
            ->where($where)
            ->where($paramWhere)->group('post.id')
            ->order($order);   

加多一个 '->group('post.id')'

**Comment by thinkcmf** [comment]
@Thomastar 可以

**Comment by thinkcmf** [comment]
@Thomastar 已经更改
