### ISSUE TITLE
安装过RC版本，重装ThinkCMF-5.0.170927失败

### ISSUE THREAD

**Issue by mysteryufo** [thinkcmf/thinkcmf#399]
前几天安装过ThinkCMF-5.0.170927-rc.zip
环境：WIN10 x64本机
WAMPSERVER3.0,PHP5.6.16,MYSQL5.7.9
新手学习重装，在WAMPSERVER里把原THINKCMF数据库删除，所有配置不变
LoadModule rewrite_module modules/mod_rewrite.so
AllowOverride All
执行安装，环境配置，SQL都正常运行，无奈最后就报了个网站创建失败，无解。。。
……
 116.SQL执行成功!
 数据库安装完成!
数据配置文件写入成功!
网站创建失败!

**Comment by mysteryufo** [comment]
官网下载wampserver3.1.0_x64，重装解决

**Comment by thinkcmf** [comment]
en
