### ISSUE TITLE
如何在本地数据库已经有了一个cmf项目之后，再重新建立一个项目？

### ISSUE THREAD

**Issue by afatshiba** [thinkcmf/thinkcmf#402]
当前本地上已经有了个cmf项目，在通过引导创建一个新的项目时，会提示有101sql 错误，如果手动把sql语句，在数据库中创建，是可以成功的，对于这种情况，应该如何在本地创建多个项目？

**Comment by shchenjianhua** [comment]
创建项目的时候更改表前缀或者重新取一个数据库名
