### ISSUE TITLE
【error，170927升级到180123】Cannot declare class app\portal\api\CategoryApi, because the name is already in use

### ISSUE THREAD

**Issue by looxii** [thinkcmf/thinkcmf#414]
170927升级到180123后：设置-》导航管理-》所有导航-》（任选一项）-》菜单管理-》添加菜单，报错：Cannot declare class app\portal\api\CategoryApi, because the name is already in use

**Comment by looxii** [comment]
Don't have a app copy or backup in the same dir and pay attention to there namespaces.

**Comment by jsRuner** [comment]
本地正常。提供下环境吧。例如php版本

**Comment by thinkcmf** [comment]
是不是复制 portal目录了
