### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by CallMeR** [thinkcmf/thinkcmf#416]
测试环境为
LNMP：
Ubuntu 16.04
Tengin 2.2.2
MariaDB 10.2.12
PHP：7.2.1
-------------------------------------------------------------------------------------------------------------------
当在网站后台的清除缓存按钮是系统抛出异常：
[8192] ErrorException in Dir.php line 88
Function create_function() is deprecated
`                $dir[$i]['ext'] = is_file($file) ? strtolower(substr(strrchr(basename($file), '.'), 1)) : '';
                $dir[$i]['mtime'] = filemtime($file);
                $dir[$i]['isDir'] = is_dir($file);
                $dir[$i]['isFile'] = is_file($file);
                $dir[$i]['isLink'] = is_link($file);
                //$dir[$i]['isExecutable']= function_exists('is_executable')?is_executable($file):'';
                $dir[$i]['isReadable'] = is_readable($file);
                $dir[$i]['isWritable'] = is_writable($file);
            }
            $cmp_func = create_function('$a,$b', '
			$k  =  "isDir";
			if($a[$k]  ==  $b[$k])  return  0;
			return  $a[$k]>$b[$k]?-1:1;
			');
            // 对结果排序 保证目录在前面
            usort($dir, $cmp_func);
            $this->_values = $dir;
            $_listDirs[$guid] = $dir;
        } else {`
-------------------------------------------------------------------------------------------------------------------
应该是和PHP7.2.1的更新有关，暂未确认该报错是否对清除缓存功能是否有影响。
8D

**Comment by Aitkots** [comment]
啊咧，为啥变成粗体字了。。。XD

**Comment by jsRuner** [comment]
和 #424  属于一个问题。
