### ISSUE TITLE
模版json配置文件中，单纯的image变量，上传不了图片

### ISSUE THREAD

**Issue by ZhangHblog** [thinkcmf/thinkcmf#42]
"about_img": {
"title": "公司图片",
"value": "/public/themes/quanmingxin/public/images/about.jpg",
"type": "image",
"tip": "",
"rule": {
"require": true
}
}
发现生成页面中对应的图片id 中带有 [ 与 ]  大括号，jquery 不能识别

**Comment by thinkcmf** [comment]
图片id 你是指的 varName吗？ varName不能有[]特殊符号

**Comment by ZhangHblog** [comment]
不是 varName ，是$inputName，像上面json 生成的id就是，id="js-widget_vars[features]-about_img-input-preview",这样的id  jquery写法是找不到的，纯js  可以

**Comment by ZhangHblog** [comment]
我是在public\themes\admin_simpleboot3\admin\theme\functions.html
<case value="image">
下把$inputName过滤掉 [ ] 后的值$newinputName
替换下面id中的$inputName
不改变name下面的$inputName
改变name   保存是会找不到数据

**Comment by ZhangHblog** [comment]
好像只有  "widgets": {}下面才会出现

**Comment by thinkcmf** [comment]
@ZhangHblog  好的，我明白了

**Comment by thinkcmf** [comment]
@ZhangHblog 已经修复请测试
