### ISSUE TITLE
Thinkcmf5的ThinkCMF模板开发教程 里 文章模板示例代码有错误

### ISSUE THREAD

**Issue by zhlkls** [thinkcmf/thinkcmf#422]
原代码地址: https://www.kancloud.cn/thinkcmf/theme_tutorial/495192 [调用文章的附件]

`
<notempty name="article.more.files">
	<foreach name="article.more.files" item="file">
    	<a src=" {:cmf_get_file_download_url($file.url)}" title={$file.name}>下载文件</a>
    </foreach>
</notempty>`

a链接没有src属性, 应该改为href,即:

`<a href=" {:cmf_get_file_download_url($file.url)}" title={$file.name}>下载文件</a>`

**Comment by thinkcmf** [comment]
已经修复
