### ISSUE TITLE
ueditor漏洞

### ISSUE THREAD

**Issue by IanGreen** [thinkcmf/thinkcmf#431]
\thinkcmf5\public\static\js\ueditor\ueditor.config.js 368行
**_whiteList_**: {……}

\thinkcmf5\public\static\js\ueditor\ueditor.all.min.js 16行
c=b.**_whitList_**;

配置属性不统一，导致标签过滤失效，即可以在ueditor的源码界面填写<script></script>标签，并在文章详情界面运行。

**Comment by jsRuner** [comment]
能截个图吗？为嘛我没复现。。

**Comment by IanGreen** [comment]
@jsRuner 已通过邮件回复

**Comment by IanGreen** [comment]
第一步：文章管理->添加（编辑）文章->查看源代码
第二部：写script->点击源代码返回文档界面（重要）
第三步：保存
第四步：查看这篇文章


原因在GitHub上说明了，这个bug很早就有（至少GitHub上cmfx2.~版本就有）。






在2018年03月19 17时44分, "吴文付"<notifications@github.com>写道:



能截个图吗？为嘛我没复现。。

**Comment by thinkcmf** [comment]
已经看明白
