### ISSUE TITLE
5.0.180123正式版后台菜单删除问题

### ISSUE THREAD

**Issue by idhuanghui** [thinkcmf/thinkcmf#435]
官方下载的5.0.180123 版本 ,  后台删除分类的时候有个小BUG,删除文章的时候会将文章状态(status)置为1(隐藏状态).但是在删除分类的时候却仍能检索到这篇已删除的文章导致分类无法删除,需要修改下AdminCategoryController文件中274行的代码

**Comment by jsRuner** [comment]
存在文章，自然无法删除分类。你可以选择去回收站彻底删除文章，就可以删除分类了。
