### ISSUE TITLE
启用七牛云插件，文章附件地址错误

### ISSUE THREAD

**Issue by yyqddm** [thinkcmf/thinkcmf#437]
当启用七牛云插件以后，新建文章，上传附件，上传rar附件以后，保存文章，在编辑文章页面看到的附件下载地址为：http://localhost/public/upload/FuAQcmMAaqW-k8pByKzIcREk3vLC
这个地址无法访问。
登录七牛云查看内容，上传的rar文件被重命名为：FuAQcmMAaqW-k8pByKzIcREk3vLC，扩展名rar丢失。

---------------------------------------------------------------------------------------------------
更新：下载地址不对的问题找到了，需要在 文件存储--存储类型 里选择 七牛云存储。
           扩展名丢失的问题还是存在。

**Comment by thinkcmf** [comment]
已经修复
