### ISSUE TITLE
Call to undefined function think\captcha\imagettftext()

### ISSUE THREAD

**Issue by cos800** [thinkcmf/thinkcmf#439]
![image](https://user-images.githubusercontent.com/635184/37698515-4022598c-2d1e-11e8-85fa-128772e689b4.png)
![image](https://user-images.githubusercontent.com/635184/37698572-789cd972-2d1e-11e8-832d-28b5e8ea0e80.png)

**Comment by jsRuner** [comment]
查看下扩展，gd扩展是否正常安装。例如 


GD Support | enabled
-- | --
GD Version | bundled (2.1.0 compatible)
FreeType Support | enabled
FreeType Linkage | with freetype
FreeType Version | 2.5.2
GIF Read Support | enabled
GIF Create Support | enabled
JPEG Support | enabled
libJPEG Version | 6b
PNG Support | enabled
libPNG Version | 1.2.50
WBMP Support | enabled
XBM Support | enabled

**Comment by abdushkur** [comment]
i found this in php.net
 "Note: This function is only available if PHP is compiled with freetype support (--with-freetype-dir=DIR)"
i use docker, php8.0 , below worked for me
`RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
        libmcrypt-dev \
        libjpeg62-turbo-dev \
        libjpeg-dev \
        libpng-dev \
        libonig-dev \
        libxpm-dev \
        libzip-dev \
        libwebp-dev \
    && docker-php-ext-install iconv \
    && docker-php-ext-configure gd \
        --with-freetype=/usr/include/freetype2 \
        --with-jpeg=/usr/include \
        --with-webp --with-xpm \
    && docker-php-ext-install -j$(nproc) gd zip\
    && docker-php-ext-enable gd `
