### ISSUE TITLE
导航标签的$level值有问题

### ISSUE THREAD

**Issue by lymanhp** [thinkcmf/thinkcmf#45]
默认的标签 输出的，菜单是二级的，第二个菜单是有下级菜单 ，其余的都是一级菜单 。输出源码如下
<ul id="main-menu" class="">
                <li class="menu-item menu-item-level-1">
    
                <a href="/" target="">
                    总校首页                </a>
            
    </li>
    <li class="dropdown dropdown-custom dropdown-custom-level-1">
        
                <a href="#" class="dropdown-toggle dropdown-toggle-1" data-toggle="dropdown">
                    院区分校<span class="caret"></span>
                </a>
            
        <ul class="dropdown-menu dropdown-menu-level-1">
                            <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/9.html" target="">
                    济南分校                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/10.html" target="">
                    厦门分校                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/11.html" target="">
                    山东分校                </a>
            
    </li>
        </ul>
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/12.html" target="">
                    专家团队                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/17.html" target="">
                    康复中心                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/16.html" target="">
                    康复案例                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/list/index/id/18.html" target="">
                    培训指南                </a>
            
    </li>
    <li class="menu-item menu-item-level-2">
    
                <a href="/portal/page/index/id/32.html" target="">
                    来校路线                </a>
            
    </li>

    </ul>

**Comment by thinkcmf** [comment]
已经修复请测试

**Comment by thinkcmf** [comment]
@lymanhp 已经修复请测试
