### ISSUE TITLE
bug 不知道算不算bug   后台菜单导入

### ISSUE THREAD

**Issue by yangguangwuwu** [thinkcmf/thinkcmf#5]
后台菜单导入，只能导入新的   
老的提示是更新 其实没有更新
例如 导航管理  这个控制器是没有自动导入注释的  添加导入注释  改个名字   界面显示更新过了
F5 刷新之后 还是老菜单名

**Comment by yangguangwuwu** [comment]
另外 手动添加菜单不能用  提示消息说服务器错误

**Comment by thinkcmf** [comment]
导入机制是,如果菜单已经存在,就只会更新菜单的父级,其它不更新,以你在后台设置的为优先@ @yangguangwuwu
