### ISSUE TITLE
从5.0.181212升级到5.0.190111后config.php内的view_replace_str被覆盖替换

### ISSUE THREAD

**Issue by hxywuya** [thinkcmf/thinkcmf#555]
最近发现接七牛云开始报错，于是就把thinkcmf升级到了5.0.190111之后发现在config.php内配置的view_replace_str无效。
经过调查发现在 AdminBaseController以及HomeBaseController内的_initializeView方法相较旧版本少了一行
`$viewReplaceStr = array_merge(config('view_replace_str'), $viewReplaceStr);`

而导致直接覆盖替换了view_replace_str

**Comment by thinkcmf** [comment]
你在view_replace_str里设置了什么？

**Comment by hxywuya** [comment]
````
'view_replace_str'        => [
        '__VUE_VERSION__'       => '2.5.17',
        '__ELEMENT_VERSION__' => '2.4.8',
        '__AXIOS_VERSION__'     => '0.18.0'
    ],
````
就如上的设置，升级前是好的，查了代码发现是合并的代码被移除了，升级教程也并没有提到有什么更改

**Comment by thinkcmf** [comment]
5.0.190312已经恢复了
