### ISSUE TITLE
5.0.190312 ErrorException in Plugin.php line 65 Use of undefined constant WEB_ROOT - assumed 'WEB_ROOT'

### ISSUE THREAD

**Issue by wmainng** [thinkcmf/thinkcmf#576]
$this->getConfig();获取配置文件时出现的,更换Plugin.php这行为之前的 $this->pluginPath     = PLUGINS_PATH . $nameCStyle . '/';

**Comment by thinkcmf** [comment]
index.php 有没有更新？
