### ISSUE TITLE
 swoole 启动 Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS'

### ISSUE THREAD

**Issue by hlovingness** [thinkcmf/thinkcmf#591]

**Comment by phcsea** [comment]
I had same problem，do you solve it?

**Comment by thinkcmf** [comment]
swoole扩展安装了吗？能不能定位到具体哪一行代码？

**Comment by hlovingness** [comment]
> swoole扩展安装了吗？能不能定位到具体哪一行代码？
## 不能，启动就出现这个，没有其他提示信息
![微信截图_20190418184053](https://user-images.githubusercontent.com/16331459/56355732-a55bdf00-6209-11e9-9362-896d475253d1.png)

**Comment by yangguangwuwu** [comment]
swoole扩展没安装把

**Comment by phcsea** [comment]
好的，非常感谢您。下午在Win10系统下安装一下扩展试试，如果还是不行的话，再咨询你哈！------------------ 原始邮件 ------------------
发件人: "王磊"<notifications@github.com>
发送时间: 2019年4月19日(星期五) 中午11:27
收件人: "thinkcmf/thinkcmf"<thinkcmf@noreply.github.com>;
抄送: "phcsea"<1051763741@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [thinkcmf/thinkcmf]  swoole 启动 Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS' (#591)



swoole扩展没安装把
 
&mdash;

**Comment by yangguangwuwu** [comment]
swoole的环境是 linux

**Comment by phcsea** [comment]
https://www.swoole.com/page/download
这是官网提供的windows版本地址，不过不怎么好用。
谢谢您的辛苦解答！ 
------------------
野心勃勃，大智若愚，韬光养晦，大胆主动出击，虚心请教，站在别人的角度思考，微笑对人。决心成为一棵大树！！！


 




------------------ 原始邮件 ------------------
发件人: "王磊"<notifications@github.com>; 
发送时间: 2019年4月19日(星期五) 下午2:42
收件人: "thinkcmf/thinkcmf"<thinkcmf@noreply.github.com>; 
抄送: "庞海藏"<1051763741@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [thinkcmf/thinkcmf]  swoole 启动 Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS' (#591)




swoole的环境是 linux
