### ISSUE TITLE
后台可不可以支持新增钩子和插件

### ISSUE THREAD

**Issue by hlovingness** [thinkcmf/thinkcmf#601]

**Comment by thinkcmf** [comment]
钩子是程序员自己加的,看一下https://www.kancloud.cn/thinkcmf/doc5_1/957873

**Comment by hlovingness** [comment]
> 钩子是程序员自己加的,看一下https://www.kancloud.cn/thinkcmf/doc5_1/957873

我知道，我在一个cms里面看到，后台可以新建钩子，插件，然后生成配置文件和一些插件默认的文件，创建插件时候可以绑定钩子，这样就省去了一些查看配置文件配置方法的时间
