### ISSUE TITLE
绕过后台地址限制BUG

### ISSUE THREAD

**Issue by qyking** [thinkcmf/thinkcmf#617]
访问/admin/public/login.html可直接来到登入页

**Comment by gengqiupeng** [comment]
注意到一个现象
在后台加密码中，设置了路由后，使用密码url访问，会自动跳转到/admin/public/login.html
这之后一直可以使用/admin/public/login.html进行访问，也就是密码失效了。

这时候清除cookie PHPSESSID，/admin/public/login.html会自动跳转到首页，密码又可用了

**Comment by lwhero** [comment]
如果修复此问题？

**Comment by thinkcmf** [comment]
就是这样设计的，已经登录过的用户后台加密码对他们是无效的，cookie或session清空后才要验证后台加密码
