### ISSUE TITLE
5.1.3新装完 "清除缓存" 功能报错

### ISSUE THREAD

**Issue by melontaro** [thinkcmf/thinkcmf#635]
`[8] ErrorException in Dir.php line 78
filetype(): Unknown file type (0)
                $dir[$i]['pathname'] = realpath($file);
                $dir[$i]['owner'] = fileowner($file);
                $dir[$i]['perms'] = fileperms($file);
                $dir[$i]['inode'] = fileinode($file);
                $dir[$i]['group'] = filegroup($file);
                $dir[$i]['path'] = dirname($file);
                $dir[$i]['atime'] = fileatime($file);
                $dir[$i]['ctime'] = filectime($file);
                $dir[$i]['size'] = filesize($file);
                $dir[$i]['type'] = filetype($file);
                $dir[$i]['ext'] = is_file($file) ? strtolower(substr(strrchr(basename($file), '.'), 1)) : '';
                $dir[$i]['mtime'] = filemtime($file);
                $dir[$i]['isDir'] = is_dir($file);
                $dir[$i]['isFile'] = is_file($file);
                $dir[$i]['isLink'] = is_link($file);
                //$dir[$i]['isExecutable']= function_exists('is_executable')?is_executable($file):'';
                $dir[$i]['isReadable'] = is_readable($file);
                $dir[$i]['isWritable'] = is_writable($file);
            }`
报错行
"$dir[$i]['type'] = filetype($file);"

**Comment by yangguangwuwu** [comment]
检查文件权限 所属组 所属人

**Comment by melontaro** [comment]
ok ,thanks.

**Comment by melontaro** [comment]
> 检查文件权限 所属组 所属人

您好,请问具体修改哪个文件夹的权限呢?我尝试吧data目录的(adminstor,user,guest,everyone)等权限都设置了读写,测试还是不行,后来把总目录权限也这只读写,还是报错.
系统环境,window10 pro,cmf5.1.5

**Comment by jsRuner** [comment]
和 #682 应该是同一个问题。已经修复了。

**Comment by melontaro** [comment]
> 和 #682 应该是同一个问题。已经修复了。
谢谢指教。
