### ISSUE TITLE
角色管理，添加角色 ，编辑角色。一处文字错误。

### ISSUE THREAD

**Issue by xskjs888** [thinkcmf/thinkcmf#66]
重复处： {:lang('ROLE_DESCRIPTION')}  

代码片段
<div class="form-group">
				<label for="input-remark" class="col-sm-2 control-label">{:lang('ROLE_DESCRIPTION')}</label>
				<div class="col-md-6 col-sm-10">
					<textarea type="text" class="form-control" id="input-remark" name="remark"></textarea>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">{:lang('ROLE_DESCRIPTION')}</label>
				<div class="col-md-6 col-sm-10">
					<label class="radio-inline">
						<input type="radio" name="status" value="1"> {:lang('ENABLED')}
					</label>
					<label class="radio-inline">
						<input type="radio" name="status" value="0"> {:lang('DISABLED')}
					</label>
				</div>
			</div>

**Comment by thinkcmf** [comment]
@xskjs888 已经修复，测试没有问题后请关闭这个 issue
