### ISSUE TITLE
分页渲染无效

### ISSUE THREAD

**Issue by joey2017** [thinkcmf/thinkcmf#679]
我在管理后台使用如下代码：
$results = UserModel::where(['user_status' => 1])->paginate(10);
$this->assign('page', $results->render());
结果我打印$results->render()是null，导致分页数据无法显示，而且我发现不但是我新增功能模块列表页无法分页渲染，就连安装好thinkcmf自带的模块也是没有分页的
![image](https://user-images.githubusercontent.com/24761416/95806711-e66b7b80-0d3a-11eb-8158-6d5526929f61.png)
这是为什么呢？我该如何做才能渲染分页？

**Comment by thinkcmf** [comment]
只有1条数据没法分页，多条数据才有分页的基础

**Comment by joey2017** [comment]
@thinkcmf 
![image](https://user-images.githubusercontent.com/24761416/96007090-be7e3400-0e70-11eb-99bd-1e1e9c5930e4.png)这种多条也没有

**Comment by joey2017** [comment]
@thinkcmf 我知道了，只有一页的都不显示分页数据
