### ISSUE TITLE
邮件模板设置报错

### ISSUE THREAD

**Issue by manbuheiniu** [thinkcmf/thinkcmf#68]
点/admin/mailer/template.html?template_key=verification_code链接设置数字验证码模板时提示**未定义变量: template**
https://github.com/thinkcmf/thinkcmf/blob/master/app/admin/controller/MailerController.php#L86
本行
`$this->assign($template);`
应该修改为
`$this->assign(“template”,$template);`
来传值。

**Comment by thinkcmf** [comment]
@manbuheiniu 已经修复，请测试
