### ISSUE TITLE
php7.4  设置--网站信息报错 banned_usernames未定义

### ISSUE THREAD

**Issue by joyokim** [thinkcmf/thinkcmf#683]
修改位置：public/theme/admin_simpleboot3/admin/setting/site.html
代码行数：199行左右 可通过关键词查找
改进代码：当空值设置默认值default=‘’
<textarea class="form-control" id="input-banned_usernames" name="cmf_settings[banned_usernames]">{$cmf_settings.banned_usernames|default=''}</textarea>

**Comment by jsRuner** [comment]
最新版本已经修复
