### ISSUE TITLE
修改了conf文件后 无法访问页面 提示该页面无法正常运作 报500错误

### ISSUE THREAD

**Issue by phynero** [thinkcmf/thinkcmf#69]
我把网站路径换成了/home/phynero/thinkcmf/public 下层就是index.php

配置文件这么改的
<Directory "/home/phynero/thinkcmf/public">
Options Indexes FollowSymLinks 
AllowOverride All
Order Deny,Allow
Allow from all  

</Directory>

项目文件夹权限直接全部777

目前情况是 index.php文件无法访问 然后同目录下的一个普通php文件可以访问
求问如何解决 百度查了好久 没有头绪

环境centos6.5  apache2.2.15  php5.3.3

之前没有修改目录的时候   把项目放到目录下 通过localhost/public/index.php是没问题的

**Comment by thinkcmf** [comment]
@phynero php 要5.4+

**Comment by phynero** [comment]
@thinkcmf 升级到了php5.5 貌似还是不行

**Comment by thinkcmf** [comment]
@phynero 那不好说了，加老猫 QQ，让他给你解决一下，可能就是环境问题

**Comment by phynero** [comment]
@thinkcmf  暂时先用别的练了  等回头熟悉点了再说  现在问估计听不懂
