### ISSUE TITLE
TP 的路由功能只在api中生效

### ISSUE THREAD

**Issue by aofall** [thinkcmf/thinkcmf#690]
今天写路由时遇到 route.php 只在 api 里生效，而 app 中的 route.php 无法作用。

然后发现了app的入口文件并没有定义路由目录，而API的入口文件定义了，想知道这是因为疏忽还是什么原因呢

```
// 定义路由目录
define('ROUTE_PATH', APP_PATH . 'route.php');
```

**Comment by BenZ-CN** [comment]
路由导入逻辑
https://github.com/thinkcmf/cmf-route/blob/6.0/src/Http.php ->loadRoutes()

api路由也有类似问题。
