### ISSUE TITLE
后台，添加菜单bug

### ISSUE THREAD

**Issue by ldq1101** [thinkcmf/thinkcmf#693]
ErrorException in Tree.php(146) : eval()'d code line 1

**Comment by ldq1101** [comment]
未定义变量: name

**Comment by php-maybe** [comment]
在Tree.php中
![image](https://user-images.githubusercontent.com/24823795/101320363-932b2a80-389e-11eb-96ea-d1c6cc9c9928.png)
第82行修改为
```
$newArr[$id] = is_array($a) ? $a : $a->toArray();
```

**Comment by thinkcmf** [comment]
已经修复
