### ISSUE TITLE
cmf5.1 视频上传时报错：文件夹已存在

### ISSUE THREAD

**Issue by gengqiupeng** [thinkcmf/thinkcmf#698]
报错代码如下
vendor/thinkcmf/cmf/src/lib/Upload.php line 127
```
$targetDir = Env::get('runtime_path') . "upload" . DIRECTORY_SEPARATOR . $userId . DIRECTORY_SEPARATOR; // 断点续传 need
        if (!file_exists($targetDir)) {
            mkdir($targetDir, 0777, true);
        }
```
复现步骤：后台文章管理，上传视频时出现
错误原因：$targetDir 应该是个文件夹，所以if判断应该用is_dir
错误截图
![QQ截图20210122165032](https://user-images.githubusercontent.com/13412304/105468454-f7307380-5cd1-11eb-8a40-a9ed7512ee03.png)

**Comment by thinkcmf** [comment]
已经优化
