### ISSUE TITLE
为传上传文件提示出错

### ISSUE THREAD

**Issue by 592645249** [thinkcmf/thinkcmf#7]
上传文件的时候提示出错。$finfo = finfo_open(FILEINFO_MIME_TYPE);这个地方出错
我后来研究发现
   $arrInfo   = ["name"  => $fileImage->getFilename(),
                              "type"  => $fileImage->getMime(),
                              "tmp_name"=>$strSaveFilePath . $strFilePath,
                              "error" => 0,
                              "size"  => $fileImage->getSize(),
                ];
在这里调用$fileImage->getMime();出错。不知道到这里调用出于 什么作用

**Comment by chengjin005** [comment]
你打开你调试看下，一般都是少扩展导致的。
