### ISSUE TITLE
thinkcmf 6.0 导入新菜单报错

### ISSUE THREAD

**Issue by hsu282** [thinkcmf/thinkcmf#700]
从后台菜单 ，所有菜单，导入新菜单时，会报错（按照后没操作其他）
#0 [2]ErrorException in AnnotationParser.php line 71
Use of undefined constant T_NAME_RELATIVE - assumed 'T_NAME_RELATIVE' (this will throw an Error in a future version of PHP)

**Comment by thinkcmf** [comment]
php版本是多少？

**Comment by hsu282** [comment]
7.4 和 7.3 都一样



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ThinkCMF"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 晚上6:46
收件人: "thinkcmf/thinkcmf"<thinkcmf@noreply.github.com&gt;; 
抄送: "79129031"<79129031@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thinkcmf/thinkcmf] thinkcmf 6.0 导入新菜单报错 (#700)





 
php版本是多少？

**Comment by hsu282** [comment]
> php版本是多少？

本地win 和服务器（linux）都出现这个问题 ，不知道是我配置问题还是程序的原因，麻烦您这边看一下是否也有同样问题

**Comment by thinkcmf** [comment]
已经修复
