### ISSUE TITLE
ThinkCMF 6.0.0 release 版本安装后demo应用未删除时导致导航添加抛错

### ISSUE THREAD

**Issue by ah-guobing** [thinkcmf/thinkcmf#701]
【环境】：PHP 7 +  ThinkCMF 6.0.0 release 版

【操作路径】：后台 - 设置 - 导航管理 - 菜单管理 - 添加菜单 （/admin/nav_menu/add.html?nav_id=1）

【Bug表现】：若默认安装后，demo应用未删除，vendor/thinkcmf/cmf-app/src/admin/model/NavMenuModel.php 第134行 $apps = cmf_scan_dir(APP_PATH . "*")  会找到 demo应用，导致业务执行时找不到  app\demo\api\PageApi 类而抛错。

**Comment by thinkcmf** [comment]
已经修复
