### ISSUE TITLE
6.0版本启用设置url美化规则后会在页面打印出路由字符串

### ISSUE THREAD

**Issue by wujchao** [thinkcmf/thinkcmf#703]
6.0版本在后台设置了url美化规则后，打开设置了url美化规则的页面时，在文档头打印了路由字符串导致文档溢出。
\/article(\/(?<id>\d+))(\/(?<cid>\d+))?<!DOCTYPE html>...

**Comment by thinkcmf** [comment]
6.0.1中已优化，年前发版本
