### ISSUE TITLE
cmf5.0版本编辑分类出现无法编辑，提示Internal Server Error

### ISSUE THREAD

**Issue by 23022340** [thinkcmf/thinkcmf#711]
编辑分类出现错误
`[8] ErrorException in PortalCategoryModel.php line 173
未定义变量: id
        return $result;
    }

    public function editCategory($data)
    {

        $result = true;

        if (!cmf_auth_check(cmf_get_current_admin_id(), "portal/Category/index?id={$id}")) {
            return false;
        }

        $id          = intval($data['id']);
        $parentId    = intval($data['parent_id']);
        $oldCategory = $this->where('id', $id)->find();

        if (empty($parentId)) {`

**Comment by lvewind** [comment]
"portal/Category/index?id={$id}" 改成 "portal/Category/index?id={$data.id}"

**Comment by yangguangwuwu** [comment]
楼上正解
