### ISSUE TITLE
更新到cmf5.1.7导致json_decode处理参数值json字符串异常！

### ISSUE THREAD

**Issue by etjson** [thinkcmf/thinkcmf#712]
前端提交的key=val中的val可能是个json字符串，5.1.6版本可以完全接收json字符串原文本，5.1.7全部被转义了，导致json字符串无法正常json_decode

**Comment by thinkcmf** [comment]
特殊字段请用`htmlspecialchars_decode()`函数解码

**Comment by etjson** [comment]
> 特殊字段请用`htmlspecialchars_decode()`函数解码

我知道用htmlspecialchars_decode，问题是接口太多，我要批量加（不规范做法），问题的所在是因为更新导致用户的项目需要改动，这不太好吧，除非说跨大版本更新，小更新目前没发生过需要改动代码的。后面不会发生了吧，我只能改框架，给底层做个判断来关闭了，毕竟代码规范是很重要的。

**Comment by etjson** [comment]
好吧，找到了，不需要做任何改动，直接配置一下关闭全局过滤就行了。
[https://github.com/thinkcmf/cmf-app/commit/36c81ef9a189e44ab9be33842a6260cd9740bd4f#diff-94a47d8ae493fd8355b2cb585e176137fe21979588dd51194eed0ff4b52dcf2d](https://github.com/thinkcmf/cmf-app/commit/36c81ef9a189e44ab9be33842a6260cd9740bd4f#diff-94a47d8ae493fd8355b2cb585e176137fe21979588dd51194eed0ff4b52dcf2d)
