### ISSUE TITLE
上传文件为blob格式时，会报错

### ISSUE THREAD

**Issue by gengqiupeng** [thinkcmf/thinkcmf#717]
cmf\lib\Upload.php 文件中 第105行会去获取文件后缀，而这里没有判断数组key是否存在

thinkcmf/cmf/src/common.php line 1385 

```
function cmf_get_file_extension($filename)
{
    $pathinfo = pathinfo($filename);
    return strtolower($pathinfo['extension']);
}
```

在上传文件类型为blob时 $pathinfo 不存在extension字段，应该从$_FILES 中获取后缀。
![image](https://user-images.githubusercontent.com/13412304/122902148-d18ebf80-d380-11eb-9293-c1823a7aaf98.png)

为什么会遇到这个问题？
更换编辑器时，TinyMCE 支持word直接导入，导入后会转换word中的图片为blob格式

**Comment by yangguangwuwu** [comment]
不对 这个 编辑器把  file 字段 的 name 变成了 blob 你应该通过设置 把 name改会file
