### ISSUE TITLE
thinkcmf6: 后台设置别名成功后  前端用别名访问 报错方法不存在

### ISSUE THREAD

**Issue by for123** [thinkcmf/thinkcmf#719]
thinkcmf 6 版本 在设置栏目别名后   路由文件中 route 中方法后多拼接了默认参数（栏目id） 导致访问别名时  报错方法不存在

![image](https://user-images.githubusercontent.com/20034438/125430612-35701016-cd78-4f37-a022-2f13cedf97fb.png)

![image](https://user-images.githubusercontent.com/20034438/125430668-3a4e077b-24a9-45f7-a2b2-7ca5e9efa852.png)

![image](https://user-images.githubusercontent.com/20034438/125430715-04353bde-4089-458e-833c-5a95b52dda84.png)

**Comment by yangguangwuwu** [comment]
已修复
