### ISSUE TITLE
插件已禁用的bug

### ISSUE THREAD

**Issue by 1120143451** [thinkcmf/thinkcmf#721]
插件安装完后，禁用插件，但是插件的后台菜单栏还是存在。而且可以访问

**Comment by 1120143451** [comment]
![image](https://user-images.githubusercontent.com/44010247/131222021-6d6116e3-b79a-41bf-9dac-b36643009fcc.png)
![image](https://user-images.githubusercontent.com/44010247/131222034-e88b0e44-754a-4368-9d4d-2e31588f8a28.png)

**Comment by qihangcn** [comment]
出现这种情况就是插件禁用了是吗？



At 2021-08-28 22:53:33, "Maple" ***@***.***> wrote:




—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1120143451** [comment]
简单的说就是如果知道插件的地址，即使插件禁用或者卸载，依然可以通过地址访问
