### ISSUE TITLE
thinkcmf  入口文件被篡改   上传后门程序一句话木马注入替换index.php

### ISSUE THREAD

**Issue by xiangyangya** [thinkcmf/thinkcmf#726]
版本v5.0.170927
后门上传位置:public/\plugins\demo\view\public\assets\images
通过访问该路径下php后门程序文件 入口文件index被替换
下面是后门程序
![image](https://user-images.githubusercontent.com/39760556/145945946-e97bc40b-2127-4888-9e7f-607195c42615.png)

**Comment by yangguangwuwu** [comment]
location ~* ^\/upload\/.+\.(html|php)$ {
        return 404;
    }
    
    location ~* ^\/plugins\/.+\.(html|php)$ {
        return 404;
    }
    
    location ~* ^\/themes\/.+\.(html|php)$ {
        return 404;
    }

**Comment by yangguangwuwu** [comment]
nginx 没配置 禁止访问
