### ISSUE TITLE
安装向导数据库验证不过

### ISSUE THREAD

**Issue by taochangle** [thinkcmf/thinkcmf#727]
排查了下， 密码里的 `<` 被转成` &lt; `了
![企业微信截图_16397231895001](https://user-images.githubusercontent.com/7435144/146500974-92e4eaf8-1ae9-406b-81b2-2391df40700a.png)
![企业微信截图_1639723202253](https://user-images.githubusercontent.com/7435144/146500981-3963ce88-a980-4bea-a227-7594618cba74.png)

**Comment by helloALin** [comment]
我也遇到同样的问题~~握爪~
先写死数据让他通过好了。

**Comment by yangguangwuwu** [comment]
c测试安装 没有发现 一遍过
