### ISSUE TITLE
6.0.4-dev安装无法完成

### ISSUE THREAD

**Issue by xdxiaodong** [thinkcmf/thinkcmf#730]
报错日志：[error] [8192]glob(): Passing null to parameter #2 ($flags) of type int is deprecated
PHP版本：8.1
报错文件：vendor/thinkcmf/cmf/src/common.php:1160
操作系统版本：macos 12.2.1
代码是通过命令php think run运行起来的

**Comment by xdxiaodong** [comment]
php8.0可以正常安装，是不支持php8.1吗？

**Comment by yangguangwuwu** [comment]
推荐8.0
