### ISSUE TITLE
新模板无法显示在模板安装列表里

### ISSUE THREAD

**Issue by xdxiaodong** [thinkcmf/thinkcmf#731]
需要修改以下文件才能显示：
vendor/thinkcmf/cmf-app/src/admin/controller/ThemeController.php
64行：`$themesDirs = cmf_scan_dir("themes/*", GLOB_ONLYDIR);`
改为
`$themesDirs = cmf_scan_dir(WEB_ROOT."themes/*", GLOB_ONLYDIR);`
74行： `$manifest = "themes/$dir/manifest.json";`
改为：
 `$manifest = WEB_ROOT."themes/$dir/manifest.json";`

**Comment by xdxiaodong** [comment]
`php think run`命令运行的新模板无法显示在模板安装列表里

**Comment by xdxiaodong** [comment]
php版本：8.0
thinkcmf版本：6.0.4-dev

**Comment by yangguangwuwu** [comment]
6.0.4
