### ISSUE TITLE
Tree有问题

### ISSUE THREAD

**Issue by xdxiaodong** [thinkcmf/thinkcmf#735]
更新到6.0.6后访问后台门户管理里的文章管理和分类管理报错：
```
#0 [0]TypeError in Tree.php line 172
str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string
```

把代码改为：`$tmpl = str_replace("{\$$key}", strval($value), $tmpl);`可以解决报错，但不清楚是否会有副作用

**Comment by thinkcmf** [comment]
已经修复，composer update试一下

**Comment by xdxiaodong** [comment]
> 已经修复，composer update试一下

已验证，问题修复了
