### ISSUE TITLE
thinkcmf网站正常运行，突然间很卡

### ISSUE THREAD

**Issue by sjkdfhjc** [thinkcmf/thinkcmf#738]
thinkcmf网站正常运行，突然间很卡。6个栏目三个打不开，三个可以打开但是超级卡。打不开的栏目页点击的瞬间服务器cpu直接冲到百分百。然后荡机打不开

**Comment by yangguangwuwu** [comment]
被攻击了， cc 或者ddos  或者是  大量请求 sql 慢查询 的地址
