### ISSUE TITLE
注册或绑定邮箱时,无法获取邮箱验证码

### ISSUE THREAD

**Issue by leejianjun** [thinkcmf/thinkcmf#739]
QQ群搜不到,没有向官方反馈问题的渠道.
请多增加几个QQ群,谢谢

**Comment by glxe** [comment]
同样的问题啊，可以用微信登录，但是绑定邮箱的时候无法发送验证码呀，可是安装的后台的模板插件啥的又需要登录市场，只能邮箱登录
