### ISSUE TITLE
后台顶部导航栏样式bug

### ISSUE THREAD

**Issue by xugar** [thinkcmf/thinkcmf#76]
打开新的标签页（openapp），那些标签的文字和关闭按钮（x）不在同一行显示了，

是装的最新的520版，前面的版本是正常的。

**Comment by xugar** [comment]
我试了下ie 和 firefox，都没问题，不知道为什么chrome就有这个问题~ 尴尬（莫非是我自己浏览器的问题）

**Comment by thinkcmf** [comment]
@xugar 请清一下浏览器缓存

**Comment by xugar** [comment]
呃，谢谢，谢谢，确实是缓存的问题。/尴尬~
