### ISSUE TITLE
注册验证码的关闭！！

### ISSUE THREAD

**Issue by shopbang** [thinkcmf/thinkcmf#81]
为了方便用户使用。
在后台应该有一个设置，可以关掉手机注册验证码和邮箱验证码。
谢谢
商场帮

**Comment by shopbang** [comment]
这个验证码最好是在后台的设置里。
单纯的一个页面。然后就两个。一个是手机验证，一个是验证，
分别有两个按钮。打开。关闭。
简单实用。可以照顾很多新手作站。
之前old cat 说手机可以关掉。但是也会有很多站为了吸引用户连邮箱验证都不会。
所以最好是有个按钮可以打开和关闭。

**Comment by thinkcmf** [comment]
@shopbang 只能关注手机注册，邮箱验证码不可能关闭的，别想了！

**Comment by shopbang** [comment]
造孽啊。。。
你就不能给大家多个选择吗。
只是个按钮的事。
我愿出2袋猫粮。

**Comment by thinkcmf** [comment]
好吧，我已经增加是否开放注册的功能
