### ISSUE TITLE
模板变量.json描述的模板变量，不能正确更新到后台模板设计中。

### ISSUE THREAD

**Issue by xskjs888** [thinkcmf/thinkcmf#9]
假如，nav.json 描述文件 原来有一个 text类型的 模板变量 ， 在后台模板设计 的模板变量中可以显示。 然后， 删掉这个变量，新增一个顶部幻灯片的模板变量。  在后台显示， 依然会显示之前 删掉的那个 text类型的模板变量。

**Comment by thinkcmf** [comment]
@xskjs888 已经修复请确认
