### ISSUE TITLE
!!!!!!!!手机注册的修改!!!!!!!!!!!

### ISSUE THREAD

**Issue by shopbang** [thinkcmf/thinkcmf#98]
手机注册.很实用.也很符合大家现在的习惯性.

但是不是所有网站,都可能开通手机短信验证码.

不废话了.

把手机注册功能留下.单独把手机注册时用的验证码给关掉.

我谢谢你!!!

**Comment by thinkcmf** [comment]
已经完善，增加是否开放注册功能
